### ISSUE TITLE
What are the edges when we select tweets as nodes?

### ISSUE THREAD

**Issue by arlorostirolla** [DocNow/twarc-network#12]
Hi! and thankyou for your very helpful library.
I'm trying to model information cascades in a tweet network, and i'm thinking it might be be more effective to use tweets/retweets as nodes. I was wondering what the edges are when you use tweets as nodes? Is it usernames who have interacted with that tweet?
Regards,
Arlo

**Comment by JoanMassachs** [comment]
Let's consider two tweets A and B: There is an edge from a A to B if A is a retweet, a reply or a quote of B. Then, the edge has only one attribute called `type` with value `retweet`, `reply` or `quote`.

The other information is stored in the nodes as attributes, that are the following:
- `user_id`: The id of the author of the tweet.
- `screen_name`: The username of the author of the tweet.
- `start_date`: The date of the first interaction that made the node appear in the graph. For example, if the node is a retweet, a reply or a quote, it is its date of creation. Or if the node is an original tweet, it is the date of the first retweet, reply or quote it received.

**Comment by arlorostirolla** [comment]
Awesome, Thankyou!
