### ISSUE TITLE
error while changing the nodes and export the data

### ISSUE THREAD

**Issue by unipdjahanifar** [DocNow/twarc-network#9]
Hi,
While I change the nodes to tweet and I want to export it I face the below error. Could you please support me?

<img width="1004" alt="image" src="https://user-images.githubusercontent.com/92152061/178475561-bfc02955-eb8a-4836-92f8-4bafbc4be640.png">

**Comment by JoanMassachs** [comment]
I think that what you want to do is this:
```twarc2 network Network-Science.jsonl --nodes tweets --format gexf Network-Science.gexf```

If you do not pass the format, the output is in html format. Therefore, in your first command you are basically converting the jsonl to html. Then, the second command fails because it founds that Network-Science.jsonl is no more a jsonl, but an html file.
